import { Roboto_Mono } from 'next/font/google'
import './globals.css'

// Definicja czcionki roboto mono
const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Przypisanie czcionki roboto mono do body ( wszystkie dzieci beda ja dziedziczyly ) */}
      <body className={robotoMono.className}>{children}</body>
    </html>
  )
}
